### ISSUE TITLE
Internal data-handling policy document

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/petitions#86]
To comply with GDPR, we need a short internal document which should be linked to from [this wiki page](https://wiki.mysociety.org/wiki/General_Data_Protection_Regulation_(GDPR)#Sites_we_host_for_others).

This should cover as many as possible of the following points. Where a point can't be answered, that may indicate that we need to create a new policy.

- What personal data we obtain from petitions
- Who has access to it - within mySociety/within the client council
- What security measures are in place
- What (if anything) we require/expect of our clients in terms of security/privacy
- What the retention period is for this data (or, if there is none, the reason why - see https://ico.org.uk/for-organisations/guide-to-data-protection/principle-5-retention/)
- What our policy is if users request that we delete their data (possibly this is managed at the client end?)
- Whether any data is or ever will be passed to third parties, eg researchers, and if so whether/how it is anonymised

As this is a Better Cities product, I'm assigning you @jukesie but feel free to pass it on to someone who can answer more quickly if needs be. Thanks!

**Comment by MyfanwyNixon** [comment]
PS although this is an internal policy, we should be happy for it to be viewed externally, eg once written,we should probably share it with client councils, and potentially they may have a clause saying that users of their website are welcome to view applicable policies on request.

**Comment by MyfanwyNixon** [comment]
Drafted at https://docs.google.com/document/d/1zLi7hnsdHDxZAD9q7ES9hXGedqTzpsJ6dhp3UYLdetg/edit

**Comment by abimysoc** [comment]
Considering this closed - the draft has been updated, and the key points have now been used externally in communications with at least a couple of councils.
