### ISSUE TITLE
Stretch Compatibility

### ISSUE THREAD

**Issue by sagepe** [mysociety/petitions#89]
We need to be able to run this on Debian Stretch, so will need to make at least the following changes:

* Add `systemd` unit file templates for the email and signup daemons;
* Support PHP7 via the fcgi wrapper;
* Update `commonlib`.

And possibly others.

**Comment by sagepe** [comment]
Notes from running the testharness on a stretch host:

* The test process needs `libwww-mechanize-perl` in `WebTestHarness.pm` and `libsys-mmap-perl` in `commonlib/perllib/mySociety/Logfile.pm`.
* `petemaild` uses `libheap-priority-perl` which we build from CPAN. This hasn't been updated in a *long* time. I have managed to build a debian package having changed a couple of `if (defined(@array))` calls in one of the test scripts to just `if (@array)`, but see the following error when running the tests: `Can't locate package AutoLoader for @Heap::Priority::ISA at ./petemaild line 916.`. Adding `use AutoLoader` into `Priority.pm` removes the error, but I'm not certain if this is the correct solution.
* The testharness then fails due to a deprecation warning `Methods with the same name as their class will not be constructors in a future version of PHP; Petition has a deprecated constructor in /data/vhost/petitions.test.mysociety.org/petitions/phplib/petition.php on line 96`. Given this is a deprecation warning, the question is whether we want to fix this now, or adjust the test process to perhaps warn and continue rather than die.

Full output of the run, having made a temporary change to `Priority.pm` to `use AutoLoader;` before `@ISA = qw (AutoLoader);`:

```
Tue Jun 12 10:35:28 2018 Set up web test harness...
Tue Jun 12 10:35:29 2018 Starting daemons...
Tue Jun 12 10:35:29 2018 Syntax check all PHP files...
Tue Jun 12 10:35:35 2018 Create petition, sign it, sign duplicate, wait until completion, send two government responses
Tue Jun 12 10:35:35 2018   Check front page works
Tue Jun 12 10:35:35 2018   Create a new petition
[Tue Jun 12 10:35:35.393489 2018] [fcgid:warn] [pid 31168:tid 139949940623104] [client 127.0.0.1:59852] mod_fcgid: stderr: PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Petition has a deprecated constructor in /data/vhost/petitions.test.mysociety.org/petitions/phplib/petition.php on line 96, referer: http://petitions.test.mysociety.org
 at ../commonlib/perllib/mySociety/WebTestHarness.pm line 47.
	mySociety::WebTestHarness::__ANON__("[Tue Jun 12 10:35:35.393489 2018] [fcgid:warn] [pid 31168:tid"...) called at ../commonlib/perllib/mySociety/WebTestHarness.pm line 615
	mySociety::WebTestHarness::log_watcher_check(mySociety::WebTestHarness=HASH(0x55c3158521c0)) called at ../commonlib/perllib/mySociety/WebTestHarness.pm line 525
	mySociety::WebTestHarness::_browser_html_hook(mySociety::WebTestHarness=HASH(0x55c3158521c0)) called at ../commonlib/perllib/mySociety/WebTestHarness.pm line 400
	mySociety::WebTestHarness::browser_follow_link(mySociety::WebTestHarness=HASH(0x55c3158521c0), "text_regex", qr(Create a petition)) called at ./test-run line 201
	main::do_create_part(HASH(0x55c315d4a840), HASH(0x55c315abeb10)) called at ./test-run line 226
	main::do_main_test() called at ./test-run line 130
in /data/servers: su - pet-testharness -c cd "/data/vhost/petitions.test.mysociety.org/petitions/bin" && ./test-run --verbose=1: system: exited with status 255 at /data/mysociety/bin/../perllib/mySociety/SystemMisc.pm line 332.
```

**Comment by sagepe** [comment]
I've done a bit of reading into the [deprecation warning](http://php.net/manual/en/migration70.deprecated.php) and it seems [it may be a simple fix](http://php.net/manual/en/language.oop5.decon.php), so an attempt at this can be seen [here](https://github.com/mysociety/petitions/blob/stretch-compat/phplib/petition.php#L104).

The test process then continued, failing again due to the need to install `php-mbstring`.

**Comment by sagepe** [comment]
The test failed at the confirm petition stage with `not found even after 61 sec wait` but the email was delivered and loaded into the database. A quick look at the test script suggests that it wasn't found as the [test script looks for Subject then To](https://github.com/mysociety/petitions/blob/stretch-compat/bin/test-run#L243) and in this instance the headers were the other way around. Running the query manually with these reversed finds the message.

**Comment by dracos** [comment]
Yeah, it's nastily brittle, see e.g. last time I did it at https://github.com/mysociety/petitions/commit/9029b1b11b7e9d7671ba6de8a80c951dd3f132da#diff-4b4d4b7de581f4875ee9917d1f907f11 (rather than try and fix this somehow).

**Comment by dracos** [comment]
I've at last dealt with that brittleness by making email_get_containing be able to check multiple conditions not just one.

**Comment by dracos** [comment]
I've put all the stretch-test branch on my current test branch (except the systemd commit).
The tests start to run okay on firefly - if I turn off the log-checking, because the log file fills with `Can't locate object method "DESTROY"`  warning at the end of each Perl request, which I guess we'll have to track down. Can't see where it's coming from :-/
So far gets past all the tests up until the cobrand Westminster one, which currently fails because the test still gets the default cobrand, again, not sure why.

**Comment by dracos** [comment]
Sleeping for 5 it passed so it's the 5 second front page cache, maybe?
